# -*- coding: utf-8 -*-
"""Projeto_Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syP920eKIDvlq9hPWrGBLYb3FvbN1hc8
"""

# Função principal da calculadora
def calculadora():
  # Loop para permitir para permitir várias operações consecutivas
  while True:
    try:
      # Recebendo dois números do usuário
      num1 = float(input('Digite o primeiro número: '))
      num2 = float(input('Digite o segundo número: '))
    except ValueError:
      print('Erro: Por favor, digite números válidos!')
      continue

    # Exibindo opções de operações
    print('\nEscolha a operação desejada:')
    print('1 - Adição')
    print('2 - Subtração')
    print('3 - Multiplicação')
    print('4 - Divisão')

    # Recebendo a escolha do usuário
    escolha = input('Digite o número da operação: ')

    # Condicional para verificar qual operação foi escolhida
    if escolha == '1':
        resultado = num1 + num2
        print('Resultado da adição:', resultado)
    elif escolha == '2':
        resultado = num1 - num2
        print('Resultado da subtração:', resultado)
    elif escolha == '3':
        resultado = num1 * num2
        print('Resultado da multiplicação:', resultado)
    elif escolha == '4':
        if num2 != 0: # Tratando divisão por zero
            resultado = num1 / num2
            print('Resultado da divisão:', resultado)
        else:
            print('Erro: Divisão por zero não é permitida!')
    else:
        print('Opção inválida')

    # Pergunta se o usuário deseja continuar
    continuar = input('\nDeseja realizar outra operação? (s/n): ').lower()
    if continuar == 's':
      continue
    elif continuar == 'n':
      print('Encerrando a calculadora. Até mais!')
      break
    else:
      print('Entrada inválida. Encerrando a calculadora. Até mais!')
      break

# Ponto de entrada do programa
if __name__ == "__main__":
  calculadora()